/* Starter data, shared by everyone who opens the notebook.
   Entries marked unverified were assembled from public web summaries of the books (not the author's own text) and
   are flagged "check" until you edit and save them. Statuses are as of the latest book the summaries covered.
   Page numbers are deliberately left blank because they differ by edition. */
window.EMPYREAN_SEED = {
  "v": 1,
  "characters": [
    {
      "id": "s-violet",
      "name": "Violet Sorrengail",
      "group": "rider",
      "status": "active",
      "rebelChild": false,
      "notes": "Main POV. Signets: stopping time and lightning wielding. Also bonded to Andarna. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-tairn"
    },
    {
      "id": "s-xaden",
      "name": "Xaden Riorson",
      "group": "rider",
      "status": "missing",
      "rebelChild": true,
      "notes": "Wingleader of Fourth Wing and secret leader of the rebel children. Turns venin at the end of Iron Flame after channeling earth magic to save Violet; Onyx Storm opens with the question of whether he can be turned back. Reported missing at the end of Onyx Storm. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-sgaeyl",
      "fateEventId": "s-ev-if-xaden-venin",
      "venin": true
    },
    {
      "id": "s-brennan",
      "name": "Brennan Sorrengail",
      "group": "rider",
      "status": "active",
      "rebelChild": false,
      "notes": "Believed dead after the Tyrrish rebellion; Violet finds him alive in Aretia at the end of Fourth Wing. Alive at the end of Iron Flame. One Onyx Storm summary says he takes Mira and heads toward Marbh. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "fateEventId": "s-ev-fw-brennan",
      "dragonId": "s-marbh"
    },
    {
      "id": "s-mira",
      "name": "Mira Sorrengail",
      "group": "rider",
      "status": "active",
      "rebelChild": false,
      "notes": "Violet's sister. Dragon Teine is listed as green. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-teine"
    },
    {
      "id": "s-dain",
      "name": "Dain Aetos",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Wingleader of Fourth Wing by Iron Flame. Shows steadfast loyalty to Violet in Onyx Storm, even stealing from his father to help her. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-cath"
    },
    {
      "id": "s-liam",
      "name": "Liam Mairi",
      "group": "rider",
      "status": "deceased",
      "rebelChild": true,
      "notes": "Signet: farsight. Dies at Resson (Iron Flame) when Deigh is killed. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-deigh",
      "fateEventId": "s-ev-if-resson"
    },
    {
      "id": "s-sloane",
      "name": "Sloane Mairi",
      "group": "rider",
      "status": "active",
      "rebelChild": false,
      "notes": "Liam's sister, daughter of a former Lord of Tyrrendor. Her ability to siphon magic proves vital (she siphons Lilith's power into the stone in Iron Flame). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-rhi",
      "name": "Rhiannon Matthias",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Signet lets her make items disappear and reappear (summoning). A squad leader by Onyx Storm. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-feirge"
    },
    {
      "id": "s-ridoc",
      "name": "Ridoc Gamlyn",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Signet: ice wielding. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-aotrom"
    },
    {
      "id": "s-garrick",
      "name": "Garrick Tavis",
      "group": "rider",
      "status": "missing",
      "rebelChild": true,
      "notes": "One of the missing riders at the end of Onyx Storm (the only one confirmed by name in the sources I found). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "fateEventId": "s-ev-os-end",
      "dragonId": "s-chradh"
    },
    {
      "id": "s-bodhi",
      "name": "Bodhi Durran",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Rebel child. Absent when Violet wakes at Riorson House at the end of Onyx Storm. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "dragonId": "s-cuir"
    },
    {
      "id": "s-imogen",
      "name": "Imogen Cardulo",
      "group": "rider",
      "status": "active",
      "rebelChild": true,
      "notes": "Rebel child. Wiped Violet's memory of the last 12 hours at the end of Onyx Storm. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-glane"
    },
    {
      "id": "s-sawyer",
      "name": "Sawyer Henrick",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Signet reported as manipulating metals. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "dragonId": "s-sliseag"
    },
    {
      "id": "s-aaric",
      "name": "Aaric Graycastle",
      "group": "rider",
      "status": "active",
      "rebelChild": false,
      "notes": "Alive and in Violet's squad at the end of Iron Flame. Summaries describe him as King Tauri's missing son, hiding his identity, with a precognitive signet; bonded to Molvic. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "aliases": "Cam Tauri",
      "dragonId": "s-molvic"
    },
    {
      "id": "s-lilith",
      "name": "Lilith Sorrengail",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "notes": "General and storm wielder; Violet's mother. She and Aimsir sacrifice themselves at the end of Iron Flame. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-aimsir",
      "fateEventId": "s-ev-if-lilith"
    },
    {
      "id": "s-jack",
      "name": "Jack Barlowe",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Survives Violet dropping a mountain on him because he turns venin. In Iron Flame he kills his own dragon Baide, which cracks the wardstone and drops Basgiath's wards. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-baide",
      "venin": true
    },
    {
      "id": "s-melgren",
      "name": "General Melgren",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-codagh"
    },
    {
      "id": "s-tynan",
      "name": "Tynan",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "notes": "Joined Jack Barlowe and Oren Seifert in an attempt on Andarna during Threshing; incinerated by Tairn. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-soleil",
      "name": "Soleil Telery",
      "group": "rider",
      "status": "deceased",
      "rebelChild": true,
      "notes": "Dies in the same battle at Resson as Liam (Iron Flame). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "fateEventId": "s-ev-if-resson"
    },
    {
      "id": "s-quinn",
      "name": "Quinn Hollis",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "notes": "Stabbed by a venin and dies in Imogen's arms during the battle at Draithus (Onyx Storm). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "fateEventId": "s-ev-os-draithus"
    },
    {
      "id": "s-trager",
      "name": "Trager",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "notes": "Shot during the game on Zehyllna; his gryphon Sila dies shortly after (Onyx Storm). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "fateEventId": "s-ev-os-zehyllna"
    },
    {
      "id": "s-aura",
      "name": "Aura Beinhaven",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "notes": "Killed by a wyvern's claws while the riders were escaping (Onyx Storm). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-oren",
      "name": "Oren Seifert",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "notes": "Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-mason",
      "name": "Mason Sanborn",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-carrigan",
      "name": "Carrigan Wyckley",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-cerella",
      "name": "Cerella Wyckley",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-jace",
      "name": "Jace Sutherland",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-bryn",
      "name": "Bryn",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-howell",
      "name": "Howell",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-weylan",
      "name": "Weylan",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-keanan",
      "name": "Keanan",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-eya",
      "name": "Eya",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ciaran",
      "name": "Ciaran",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-norwood",
      "name": "Norwood",
      "group": "rider",
      "status": "unknown",
      "rebelChild": true,
      "notes": "Listed among the marked rebel children. Fill in details as you read. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-berwyn",
      "name": "Berwyn",
      "group": "antagonist",
      "status": "unknown",
      "rebelChild": false,
      "venin": true,
      "notes": "Venin sage and maven (the equivalent of a general), a dream walker who throws blue fire. Summaries say he turned Xaden. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-theophanie",
      "name": "Theophanie",
      "group": "antagonist",
      "status": "deceased",
      "rebelChild": false,
      "venin": true,
      "notes": "Main antagonist of Onyx Storm: a maven and dark wielder who is also a powerful storm wielder and rides a huge wyvern. Killed by Violet, with Aaric's help, using a shard from Dunne's temple. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "fateEventId": "s-ev-os-theo"
    },
    {
      "id": "s-varrish",
      "name": "Major Burton Varrish",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Vice Commander of Basgiath War College in Iron Flame; ruthless, previously suspended for killing during his tortures. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3,
      "dragonId": "s-solas"
    },
    {
      "id": "s-kaori",
      "name": "Professor Kaori",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Dragonkind professor at Basgiath. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-grady",
      "name": "Professor Grady",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Runs the Rider Survival Course (RSC). Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-devera",
      "name": "Professor Devera",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Teaches history and Battle Brief; defects from the college to join the rebellion in Aretia. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-markham",
      "name": "Professor Markham",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Curator of the Riders Quadrant; teaches Battle Brief. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-panchek",
      "name": "Commandant Panchek",
      "group": "professor",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Identified in Onyx Storm as the traitor at Basgiath. One summary says Panchek's dragon is killed at Berwyn's hands. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-cat",
      "name": "Catriona (Cat) Cordella",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Gryphon flier of Poromiel and Xaden's ex-fiancée (betrothed for nine months). Niece of Viscount Tecarus. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "origin": "Krovla, Poromiel"
    },
    {
      "id": "s-tecarus",
      "name": "Viscount (later King) Tecarus",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Viscount of the Poromish province of Krovla. After Queen Maraya's death he becomes King of Poromiel. Has a gryphon gift for sensing what motivates someone to give up their treasure. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "origin": "Krovla, Poromiel"
    },
    {
      "id": "s-jesinia",
      "name": "Jesinia",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Scribe who reveals in Iron Flame that Andarna is the key to activating the wardstone. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-dylan",
      "name": "Dylan",
      "group": "rider",
      "status": "deceased",
      "rebelChild": false,
      "venin": false,
      "notes": "Dies on the parapet in Fourth Wing. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-syrena",
      "name": "Syrena Cordella",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Cat's older sister and Tecarus's niece. Works with Xaden to distribute stolen venin-killing daggers to fliers. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "origin": "Krovla, Poromiel"
    },
    {
      "id": "s-drake",
      "name": "Drake Cordella",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Cousin of Syrena and Cat. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "origin": "Krovla, Poromiel"
    },
    {
      "id": "s-maraya",
      "name": "Queen Maraya",
      "group": "civilian",
      "status": "deceased",
      "rebelChild": false,
      "venin": false,
      "notes": "Queen of Poromiel; Tecarus becomes king after her death. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "origin": "Poromiel"
    },
    {
      "id": "s-heaton",
      "name": "Heaton",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Violet's squadmate. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4
    },
    {
      "id": "s-naolin",
      "name": "Naolin",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Tairn's previous rider. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4
    },
    {
      "id": "s-nolon",
      "name": "Nolon",
      "group": "civilian",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Healer who mends Jack Barlowe in the infirmary after Violet drops the mountain on him. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4
    },
    {
      "id": "s-caroline",
      "name": "Caroline Ashton",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "First-year unbonded cadet in Fourth Wing until she bonds Gleann after his previous rider died during their first flight lesson. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4,
      "dragonId": "s-gleann"
    },
    {
      "id": "s-winifred",
      "name": "Winifred Colbersy",
      "group": "rider",
      "status": "unknown",
      "rebelChild": false,
      "venin": false,
      "notes": "Makes a brief appearance in the early chapters of Onyx Storm. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4
    }
  ],
  "dragons": [
    {
      "id": "s-tairn",
      "name": "Tairn",
      "color": "Black",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-violet",
      "status": "unknown",
      "notes": "Mated to Sgaeyl.",
      "unverified": false,
      "tail": "morningstartail",
      "rev": 2,
      "aliases": "Tairneanach"
    },
    {
      "id": "s-andarna",
      "name": "Andarna",
      "color": "Irid",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-violet",
      "status": "unknown",
      "notes": "Violet's second bond. Per summaries she is a breed of her own who waited about 650 years for Violet, and the key to activating the wardstone. Starter note from web summaries of the books; check against your copy.",
      "unverified": false,
      "tail": "feathertail",
      "rev": 2,
      "aliases": "Andarnaurram"
    },
    {
      "id": "s-aimsir",
      "name": "Aimsir",
      "color": "",
      "tail": "",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-lilith",
      "status": "deceased",
      "notes": "Dies with Lilith at the end of Iron Flame. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-baide",
      "name": "Baide",
      "color": "Orange",
      "tail": "scorpiontail",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-jack",
      "status": "deceased",
      "notes": "Killed by Jack Barlowe in Iron Flame, which cracks the wardstone. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-codagh",
      "name": "Codagh",
      "color": "Black",
      "tail": "swordtail",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-melgren",
      "status": "unknown",
      "notes": "Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-solas",
      "name": "Solas",
      "color": "",
      "tail": "",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-varrish",
      "status": "unknown",
      "notes": "Major Varrish's dragon. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-marbh",
      "name": "Marbh",
      "color": "Orange",
      "tail": "Dagger",
      "sex": "male",
      "family": "Fhaicorain",
      "age": 76,
      "riders": 3,
      "sire": "",
      "dam": "",
      "riderId": "s-brennan",
      "status": "unknown",
      "notes": "Brennan's dragon; in Threshing Day Brennan meets him in a tree.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-teine",
      "name": "Teine",
      "color": "Green",
      "tail": "Club",
      "sex": "male",
      "family": "Cruaidhuaine",
      "age": 41,
      "riders": 0,
      "sire": "",
      "dam": "",
      "riderId": "s-mira",
      "status": "unknown",
      "notes": "Mira's dragon.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-sgaeyl",
      "name": "Sgaeyl",
      "color": "Blue",
      "tail": "Dagger",
      "sex": "female",
      "family": "Gormfaileas",
      "age": 64,
      "riders": 3,
      "sire": "",
      "dam": "",
      "riderId": "s-xaden",
      "status": "unknown",
      "notes": "Mated to Tairn.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-chradh",
      "name": "Chradh",
      "color": "Brown",
      "tail": "Scorpion",
      "sex": "male",
      "family": "Aldayrmar",
      "age": 27,
      "riders": 0,
      "sire": "",
      "dam": "",
      "riderId": "s-garrick",
      "status": "unknown",
      "notes": "",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-cath",
      "name": "Cath",
      "color": "Red",
      "tail": "Sword",
      "sex": "male",
      "family": "Berradhdyr",
      "age": 86,
      "riders": 2,
      "sire": "",
      "dam": "",
      "riderId": "s-dain",
      "status": "unknown",
      "notes": "Dain's dragon.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-cuir",
      "name": "Cuir",
      "color": "Green",
      "tail": "Sword",
      "sex": "male",
      "family": "Uaineloidsig",
      "age": 59,
      "riders": 1,
      "sire": "",
      "dam": "",
      "riderId": "s-bodhi",
      "status": "unknown",
      "notes": "",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-glane",
      "name": "Glane",
      "color": "Orange",
      "tail": "Dagger",
      "sex": "female",
      "family": "Fhaicorain",
      "age": 19,
      "riders": 0,
      "sire": "",
      "dam": "",
      "riderId": "s-imogen",
      "status": "unknown",
      "notes": "Claimed Imogen before Threshing began. Starter note from web summaries of the books; check against your copy.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-feirge",
      "name": "Feirge",
      "color": "Green",
      "tail": "Dagger",
      "sex": "female",
      "family": "Uaineloidsig",
      "age": 87,
      "riders": 3,
      "sire": "",
      "dam": "",
      "riderId": "s-rhi",
      "status": "unknown",
      "notes": "Starter note from web summaries of the books; check against your copy.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-sliseag",
      "name": "Sliseag",
      "color": "Red",
      "tail": "Sword",
      "sex": "male",
      "family": "Berradhdyr",
      "age": 73,
      "riders": 2,
      "sire": "",
      "dam": "",
      "riderId": "s-sawyer",
      "status": "unknown",
      "notes": "",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-aotrom",
      "name": "Aotrom",
      "color": "Brown",
      "tail": "Sword",
      "sex": "male",
      "family": "Aldayrmar",
      "age": 21,
      "riders": 0,
      "sire": "",
      "dam": "",
      "riderId": "s-ridoc",
      "status": "unknown",
      "notes": "Starter note from web summaries of the books; check against your copy.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-deigh",
      "name": "Deigh",
      "color": "Red",
      "tail": "Dagger",
      "sex": "male",
      "family": "Wybjorian",
      "age": 62,
      "riders": 1,
      "sire": "",
      "dam": "",
      "riderId": "s-liam",
      "status": "deceased",
      "notes": "Killed at Resson (Iron Flame), which also kills Liam. Starter note from web summaries of the books; check against your copy.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-thoirt",
      "name": "Thoirt",
      "color": "Red",
      "tail": "Dagger",
      "sex": "female",
      "family": "Wybjorian",
      "age": 62,
      "riders": 1,
      "sire": "",
      "dam": "",
      "riderId": "",
      "status": "unknown",
      "notes": "Rider not recorded here. Shares line and age with Deigh, so possibly the sibling of Liam's dragon; set the rider once you confirm.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-molvic",
      "name": "Molvic",
      "color": "Blue",
      "tail": "Club",
      "sex": "male",
      "family": "Gormfaileas",
      "age": 39,
      "riders": 0,
      "sire": "",
      "dam": "",
      "riderId": "s-aaric",
      "status": "unknown",
      "notes": "Aaric's dragon.",
      "unverified": false,
      "rev": 4
    },
    {
      "id": "s-gleann",
      "name": "Gleann",
      "color": "",
      "tail": "",
      "sex": "",
      "family": "",
      "sire": "",
      "dam": "",
      "riderId": "s-caroline",
      "status": "unknown",
      "notes": "Bonded Caroline Ashton after his previous rider died during their first flight lesson. Starter note from web summaries of the books; check against your copy.",
      "unverified": true,
      "rev": 4
    }
  ],
  "events": [
    {
      "id": "s-ev-threshing",
      "title": "Violet's Threshing",
      "book": "FW",
      "order": 10,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Violet takes part in Threshing at Basgiath and bonds Tairn and Andarna. Add the page, chapter and details from your copy.",
      "chars": [
        "s-violet"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-fw-brennan",
      "title": "Violet learns Brennan is alive in Aretia",
      "book": "FW",
      "order": 90,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Violet wakes up at the end of Fourth Wing and discovers Brennan, believed dead after the rebellion, is alive in Aretia.",
      "chars": [
        "s-violet",
        "s-brennan"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-resson",
      "title": "Battle at Resson (Athebyne)",
      "book": "IF",
      "order": 50,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Liam and Soleil Telery die at Resson; Liam dies when Deigh is killed.",
      "chars": [
        "s-liam",
        "s-soleil"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-os-zehyllna",
      "title": "The game on Zehyllna: Trager shot",
      "book": "OS",
      "order": 40,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Trager is shot during the game on Zehyllna and his gryphon Sila dies shortly after.",
      "chars": [
        "s-trager"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-os-draithus",
      "title": "Battle of Draithus: Quinn dies",
      "book": "OS",
      "order": 50,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Quinn Hollis is stabbed by a venin and dies in Imogen's arms.",
      "chars": [
        "s-quinn",
        "s-imogen"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-os-end",
      "title": "Onyx Storm ending: the missing twelve hours",
      "book": "OS",
      "order": 99,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Violet wakes at Riorson House after killing Theophanie, wearing a wedding ring, with Imogen having wiped the last 12 hours. Xaden, Garrick, three other riders and six dragon eggs are missing. A rich ground for book 4 theories.",
      "chars": [
        "s-violet",
        "s-xaden",
        "s-garrick",
        "s-imogen"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-fw-two-dragons",
      "title": "Violet bonds two dragons: double signets",
      "book": "FW",
      "order": 12,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Violet becomes the first rider with two dragons, Tairn and Andarna, and so carries two signets: lightning wielding (Tairn) and stopping time (Andarna), per the summaries.",
      "chars": [
        "s-violet"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-channeling",
      "title": "Channeling begins",
      "book": "IF",
      "order": 30,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "After Violet stands up to Jack Barlowe's taunting without losing her temper, her dragons decide she is ready to begin channeling, the point where riders start drawing magic directly from the earth.",
      "chars": [
        "s-violet"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-andarna-ward",
      "title": "Andarna is the key to the wardstone",
      "book": "IF",
      "order": 60,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Jesinia reveals that Andarna is the secret to activating the wardstone, and that she is a breed of her own who waited about 650 years for Violet to hatch.",
      "chars": [
        "s-jesinia",
        "s-violet"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-jack-ward",
      "title": "Jack returns as venin and cracks the wardstone",
      "book": "IF",
      "order": 70,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Jack survived Violet dropping a mountain on him because he turned venin. He kills his own dragon, which cracks the wardstone in half and brings down Basgiath's wards.",
      "chars": [
        "s-jack"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-xaden-signet",
      "title": "Xaden's second signet is revealed",
      "book": "IF",
      "order": 80,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Xaden is revealed to have a second signet.",
      "chars": [
        "s-xaden"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-xaden-venin",
      "title": "Xaden channels earth magic and turns venin",
      "book": "IF",
      "order": 85,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "While Violet is burning out to save everyone, Xaden loses to a venin general. Feeling Violet dying, he channels power from the earth to save her and turns venin. Onyx Storm opens with him held at Basgiath under constant watch and the question of whether he can be turned back.",
      "chars": [
        "s-xaden",
        "s-violet"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-if-lilith",
      "title": "Lilith and Aimsir sacrifice themselves",
      "book": "IF",
      "order": 90,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Just before Violet burns out, Lilith kicks her aside and forces Sloane to siphon all her power into the stone. Lilith and Aimsir die, and the wards at Basgiath are restored.",
      "chars": [
        "s-lilith",
        "s-sloane"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-os-panchek",
      "title": "Commandant Panchek is the traitor at Basgiath",
      "book": "OS",
      "order": 60,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "Panchek is identified as the traitor at Basgiath.",
      "chars": [
        "s-panchek"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-os-theo",
      "title": "Theophanie is killed",
      "book": "OS",
      "order": 70,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Violet kills the maven Theophanie, with Aaric's help, using a shard from Dunne's temple.",
      "chars": [
        "s-violet",
        "s-theophanie"
      ],
      "unverified": true,
      "rev": 3
    },
    {
      "id": "s-ev-td-brennan",
      "title": "Threshing Day: Brennan",
      "book": "TD",
      "order": 1,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Brennan enters Threshing determined to prove himself beyond the Sorrengail name. His father gives him a good-luck bracelet, and alone he climbs a tree and meets Marbh, an orange daggertail. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-brennan"
      ],
      "unverified": true,
      "rev": 4,
      "story": 100
    },
    {
      "id": "s-ev-td-mira",
      "title": "Threshing Day: Mira",
      "book": "TD",
      "order": 2,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Teine digs a talon into Mira's thigh to find her breaking point, and she tells him to take his fingernail out of her leg. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-mira"
      ],
      "unverified": true,
      "rev": 4,
      "story": 105
    },
    {
      "id": "s-ev-fw-deal",
      "title": "Xaden's deal with General Sorrengail",
      "book": "FW",
      "order": 0,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "As the oldest of the separatist children, Xaden takes responsibility for the 107 marked children and receives 107 scars across his back, an archaic Tyrrish custom. In return General Lilith Sorrengail lets the children fight for their lives in the Riders Quadrant instead of being executed. Placement before Fourth Wing is approximate.",
      "chars": [
        "s-xaden",
        "s-lilith"
      ],
      "unverified": true,
      "rev": 4,
      "story": 108
    },
    {
      "id": "s-ev-td-xaden",
      "title": "Threshing Day: Xaden",
      "book": "TD",
      "order": 3,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Set in the snow, Xaden says he'd love nothing more than to burn the place to the ground. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-xaden"
      ],
      "unverified": true,
      "rev": 4,
      "story": 110
    },
    {
      "id": "s-ev-td-garrick",
      "title": "Threshing Day: Garrick",
      "book": "TD",
      "order": 4,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Garrick's Threshing. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-garrick"
      ],
      "unverified": true,
      "rev": 4,
      "story": 120
    },
    {
      "id": "s-ev-td-bodhi",
      "title": "Threshing Day: Bodhi",
      "book": "TD",
      "order": 5,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Bodhi's Threshing. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-bodhi"
      ],
      "unverified": true,
      "rev": 4,
      "story": 130
    },
    {
      "id": "s-ev-td-imogen",
      "title": "Threshing Day: Imogen",
      "book": "TD",
      "order": 6,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Imogen's Threshing. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-imogen"
      ],
      "unverified": true,
      "rev": 4,
      "story": 140
    },
    {
      "id": "s-ev-td-dain",
      "title": "Threshing Day: Dain",
      "book": "TD",
      "order": 7,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Dain's Threshing. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-dain"
      ],
      "unverified": true,
      "rev": 4,
      "story": 150
    },
    {
      "id": "s-ev-td-liam",
      "title": "Threshing Day: Liam",
      "book": "TD",
      "order": 8,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Liam's Threshing, on the same day as Violet's. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-liam"
      ],
      "unverified": true,
      "rev": 4,
      "story": 1010.1
    },
    {
      "id": "s-ev-td-rhi",
      "title": "Threshing Day: Rhiannon",
      "book": "TD",
      "order": 9,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Rhiannon's Threshing, on the same day as Violet's. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-rhi"
      ],
      "unverified": true,
      "rev": 4,
      "story": 1010.2
    },
    {
      "id": "s-ev-td-ridoc",
      "title": "Threshing Day: Ridoc",
      "book": "TD",
      "order": 10,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Ridoc's Threshing, on the same day as Violet's. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-ridoc"
      ],
      "unverified": true,
      "rev": 4,
      "story": 1010.3
    },
    {
      "id": "s-ev-td-sawyer",
      "title": "Threshing Day: Sawyer",
      "book": "TD",
      "order": 11,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Sawyer's Threshing, on the same day as Violet's. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-sawyer"
      ],
      "unverified": true,
      "rev": 4,
      "story": 1010.4
    },
    {
      "id": "s-ev-td-sloane",
      "title": "Threshing Day: Sloane",
      "book": "TD",
      "order": 12,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Sloane's Threshing, early in Iron Flame. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-sloane"
      ],
      "unverified": true,
      "rev": 4,
      "story": 2005.1
    },
    {
      "id": "s-ev-td-aaric",
      "title": "Threshing Day: Aaric",
      "book": "TD",
      "order": 13,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "event",
      "desc": "Aaric's Threshing, early in Iron Flame. The collection's final story has a prince in rider black telling his dragon he intends to tear the kingdom apart. Where this sits in the timeline is inferred from the rider's year at Basgiath; check against the book.",
      "chars": [
        "s-aaric"
      ],
      "unverified": true,
      "rev": 4,
      "story": 2005.2
    },
    {
      "id": "s-ev-if-deal",
      "title": "Iron Flame reveals what the deal included",
      "book": "IF",
      "order": 40,
      "chapter": "",
      "page": "",
      "edition": "",
      "kind": "reveal",
      "desc": "It comes out that the favor General Sorrengail asked of Xaden, in exchange for putting the marked ones under his oversight in the Riders Quadrant, was to keep Violet alive.",
      "chars": [
        "s-xaden",
        "s-lilith",
        "s-violet"
      ],
      "unverified": true,
      "rev": 4
    }
  ],
  "theories": [
    {
      "id": "s-th-example",
      "title": "Example theory — delete me",
      "status": "speculative",
      "confidence": 2,
      "body": "This is a placeholder showing how a theory works. Pick the timeline events that foreshadow it, then either link the event where it pays off or leave it as 'not yet revealed'. Add evidence with a book, edition and page number, and mark each piece as support or against.",
      "foreshadow": [
        "s-ev-threshing"
      ],
      "revealId": "",
      "revealText": "",
      "evidence": [
        {
          "book": "FW",
          "edition": "Hardcover",
          "page": "123",
          "note": "Example reference — replace with a real one.",
          "stance": "support"
        }
      ],
      "created": 0,
      "updated": 0
    },
    {
      "id": "s-th-imogen-trip",
      "title": "Imogen disappeared on the field trip and the memory of her being there was wiped",
      "status": "speculative",
      "confidence": 3,
      "body": "Imogen went on the field trip but did not come back with the others. Working theory: she vanished, and the memories that she was ever there were wiped. Add the scene where the group returns without her, who does and doesn't remember her, and any clue about how it was done. Per summaries, Imogen later wipes Violet's memory of twelve hours at the end of Onyx Storm, which may be related.",
      "foreshadow": [
        "s-ev-os-end"
      ],
      "revealId": "",
      "revealText": "",
      "evidence": [],
      "created": 0,
      "updated": 0
    },
    {
      "id": "s-th-blood",
      "title": "Some riders draw blood on their Threshing day",
      "status": "speculative",
      "confidence": 2,
      "body": "Several of the Threshing Day stories have a rider drawing blood during their Threshing. List which riders, what the dragon did, and whether blood changes the bond, the signet or how the dragon chooses.",
      "foreshadow": [],
      "revealId": "",
      "revealText": "",
      "evidence": [],
      "created": 0,
      "updated": 0
    },
    {
      "id": "s-th-transcribers",
      "title": "Threshing Day is transcribed by different people than the main books",
      "status": "speculative",
      "confidence": 1,
      "body": "Threshing Day credits Colonel Valin Kaori and Lieutenant Ellery Mynna with the transcription, not Jesinia Neilwart who frames the main trilogy. What does that say about who compiled it and when?",
      "foreshadow": [],
      "revealId": "",
      "revealText": "",
      "evidence": [],
      "created": 0,
      "updated": 0
    }
  ],
  "notices": [
    {
      "id": "s-n-634-23",
      "title": "Public Notice 634.23",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 634",
      "transcriber": "Percival Fitzgibbons",
      "seq": 1,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Conscription rates are doubled in every province until further notice.",
      "cites": [],
      "text": "Conscription rates are hereby doubled for each province until further notice."
    },
    {
      "id": "s-n-628-86",
      "title": "Public Notice 628.86",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 628",
      "transcriber": "Cerella Neilwart",
      "seq": 2,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "After the Treaty of Aretia, Tyrrendor's seat in the King's Senarium passes from House Riorson to House Lewellen.",
      "cites": [],
      "text": "As a result of the Treaty of Aretia, the power to represent the province of Tyrrendor in the King’s Senarium has hereby been transferred from the House of Riorson to the House of Lewellen."
    },
    {
      "id": "s-n-628-85",
      "title": "Public Notice 628.85",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 628",
      "transcriber": "Cerella Neilwart",
      "seq": 3,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Records that Aretia was burned by dragons under the treaty that ended the separatist movement. Those who fled survived; the rest remain entombed in the ruins.",
      "cites": [],
      "text": "In this, the 628th year of our Unification, it is hereby recorded that Aretia has been burned by dragon in accordance with the Treaty ending the separatist movement. Those who fled, survived, and those who did not remain entombed in her ruins."
    },
    {
      "id": "s-n-442-184",
      "title": "Public Notice 442.184",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 442",
      "transcriber": "Corrigan Aligis",
      "seq": 4,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Raiders from the Emerald Sea sacked the Tyrrish village of Kyllendelle. Seaside residents of Tyrrendor and Luceras are asked to stay vigilant and light warning beacons to call the nearest riot.",
      "cites": [],
      "text": "The Tyrrish village of Kyllendelle has been sacked by raiders from the Emerald Sea. We ask those living by the seaside in Tyrrendor and Luceras to remain vigilant in service to their fellow Navarrians and light the warning beacons to alert the nearest riot if requesting aid."
    },
    {
      "id": "s-n-433-231",
      "title": "Public Notice 433.231",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 433",
      "transcriber": "Corrigan Aligis",
      "seq": 5,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Navarrian forces repelled an attempted breach by Poromish troops near the outpost of Athebyne. The attack is called unprovoked, and the commitment to the peace process is restated.",
      "cites": [],
      "text": "Our forces have successfully routed an attempted breach of our border by Poromish forces near the outpost of Athebyne. While this attack was unprovoked, we remain committed to the peace process."
    },
    {
      "id": "s-n-210-183",
      "title": "Public Notice 210.183",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 210",
      "transcriber": "Myla Arvinset",
      "seq": 6,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Provincial notices are ended. Regional notices written by local scribes replace them, each needing approval from the Curator of the Scribe Quadrant at Basgiath before posting.",
      "cites": [],
      "text": "The system of provincial notices is hereby ended in order to simplify the flow of accurate information to all Navarrians, and will be replaced with regional notices provided by local scribes, all of which must be approved by the Curator of the Scribe Quadrant of Basgiath War College before posting."
    },
    {
      "id": "s-n-209-11",
      "title": "Public Notice 209.11",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 209",
      "transcriber": "Myla Arvinset",
      "seq": 7,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Public notices now override provincial ones, posted for up to sixty days in any village with more than five hundred people.",
      "cites": [],
      "text": "In the interest of quelling rumor and providing accurate information on behalf of the crown, all public notices hereby transcend their provincial counterparts, and will be posted for a maximum of sixty days in any village with a population greater than five hundred."
    },
    {
      "id": "s-n-208-271",
      "title": "Public Notice 208.271",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 208",
      "transcriber": "Myla Arvinset",
      "seq": 8,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Queen Alondra splits Tyrrendor into three duchies (Lewellen, Tirvainne and Aretia). The Duchess of Aretia keeps the Tyrrish seat on the Senarium.",
      "cites": [],
      "text": "Queen Alondra has ordered the provinces of Tyrrendor to be split into three duchies to better serve her citizens. While the Dukes of Lewellen and Tirvainne will oversee their territories for the betterment of all—as per the new maps provided by the crown—the Duchess of Aretia will retain the Tyrrish seat on the Senarium to represent the province."
    },
    {
      "id": "s-n-207-6",
      "title": "Public Notice 207.6",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 207",
      "transcriber": "Myla Arvinset",
      "seq": 9,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Because of increased danger, travel beyond Navarre may only be authorized by the sovereign.",
      "cites": [],
      "text": "Due to increased danger to our citizens, travel beyond Navarre may only be authorized by the sovereign."
    },
    {
      "id": "s-n-207-1",
      "title": "Public Notice 207.1",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 207",
      "transcriber": "Myla Arvinset",
      "seq": 10,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Every duchy signs a Provincial Commitment placing the provincial armies under Queen Alondra's standard against Poromish aggression until the war is declared over.",
      "cites": [],
      "text": "A Provincial Commitment has been signed by every duchy in Navarre, consolidating the provinces' armies under Queen Alondra's standard to better defend our kingdom against Poromish aggression until such time as the war is declared over."
    },
    {
      "id": "s-n-200-417",
      "title": "Public Notice 200.417",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 200",
      "transcriber": "Racel Lightstone",
      "seq": 11,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Guardians may no longer dedicate children to a favored deity. Serving the gods for life must be chosen freely after the age of majority.",
      "cites": [],
      "text": "Guardians are no longer permitted to dedicate children in service to their favored deity. The decision to serve the gods for life must be made after the age of majority and of one’s free will."
    },
    {
      "id": "s-n-2-21",
      "title": "Public Notice 2.21",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 2",
      "transcriber": "Byran Firthfelder",
      "seq": 12,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The Migration of the First Year is declared complete. Borders are secured against increasingly militant neighbors, and travel beyond Navarre may be authorized by a duchy's ruling house.",
      "cites": [],
      "text": "The triumphant success of The Migration of The First Year is now considered complete. To keep the promise of peace we fought for, our forces have taken the unfortunate, but necessary precaution of securing our borders against our increasingly militant neighbors. Travel beyond Navarre may be authorized by a duchy's ruling house."
    },
    {
      "id": "s-n-1-323",
      "title": "Public Notice 1.323",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 13,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Krovlan forces attacked Elsum, causing four casualties in the mountains near the village of Resson. The area is secured and the attack is called an outlier; the commitment to peace stands.",
      "cites": [],
      "text": "The province of Elsum has suffered an unprovoked attack by Krovlan forces, resulting in four casualties in the mountains near the village of Resson. The area has been secured. Our commitment to peace has not wavered and we consider this heinous act to be an outlier."
    },
    {
      "id": "s-n-1-249",
      "title": "Public Notice 1.249",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 14,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The Council of Calldyr agrees that Navarre is ruled as a secular kingdom, but its marriage law follows the terms each god sets in their temples.",
      "cites": [],
      "text": "The Council of Calldyr has agreed that while rule of Navarre is secular, the law of the kingdom will follow the unique terms each god has set in their temples regarding marriage."
    },
    {
      "id": "s-n-1-3",
      "title": "Public Notice 1.3",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 15,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "As promised in the Unification Scrolls, the borders stay open for twelve months to anyone who wants to live under Navarre's wards and laws.",
      "cites": [],
      "text": "As promised in the Unification Scrolls that define our laws, for the next twelve months, the borders of the Kingdom of Navarre will remain open to all who wish to live under the protection of our wards and laws. We welcome all who wish to be Navarrians."
    },
    {
      "id": "s-n-1-2",
      "title": "Public Notice 1.2",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 16,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The scribes of Basgiath War College take over announcing and recording public notices, posted beside provincial ones for at least thirty days in villages with more than fifty people.",
      "cites": [],
      "text": "In the interest of the security of Navarre and in the spirit of transparency within our unified realm, the scribes of Basgiath War College have assumed the honorable responsibility of announcing and recording all pertinent information via public notices. These notices shall be posted alongside their provincial counterparts for a minimum of thirty days in any village with a population greater than fifty."
    },
    {
      "id": "s-n-1-1",
      "title": "Public Notice 1.1",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 17,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Calldyr, Elsum, Luceras, Morainne and Tyrrendor accept the Unification Scrolls and swear fealty to King Reginald Navarrius. The kingdom is named Navarre and the calendar restarts at year 1.",
      "cites": [],
      "text": "It is hereby recorded that the territories of Calldyr, Elsum, Luceras, Morainne, and Tyrrendor have agreed to terms defined in the Unification Scrolls and sworn fealty to our magnanimous King Reginald Navarrius. All people dwelling within the safe haven of our borders shall be considered citizens of the kingdom now known as Navarre. In celebration of this momentous occasion and our new, peaceful era, our calendars shall reflect this year as our first after unification."
    }
  ]
};
