/* Starter data. Everything here was pre-filled from memory and is flagged "check" until you edit it.
   Statuses, family trees and page numbers are deliberately left for you to fill in from your own copies. */
window.EMPYREAN_SEED = {
  v: 1,
  characters: [
    { id:"s-violet",  name:"Violet Sorrengail", group:"rider", status:"unknown", rebelChild:false, dragonId:"s-tairn", notes:"Main POV.", unverified:true },
    { id:"s-xaden",   name:"Xaden Riorson",     group:"rider", status:"unknown", rebelChild:true,  dragonId:"s-sgaeyl", notes:"", unverified:true },
    { id:"s-brennan", name:"Brennan Sorrengail", group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-mira",    name:"Mira Sorrengail",   group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-dain",    name:"Dain Aetos",        group:"rider", status:"unknown", rebelChild:false, dragonId:"s-cath", notes:"", unverified:true },
    { id:"s-liam",    name:"Liam Mairi",        group:"rider", status:"unknown", rebelChild:false, dragonId:"s-deigh", notes:"", unverified:true },
    { id:"s-sloane",  name:"Sloane Mairi",      group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-rhi",     name:"Rhiannon Matthias", group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-ridoc",   name:"Ridoc Gamlyn",      group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-garrick", name:"Garrick Tavis",     group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-bodhi",   name:"Bodhi",             group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-imogen",  name:"Imogen",            group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-sawyer",  name:"Sawyer",            group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
    { id:"s-aaric",   name:"Aaric",             group:"rider", status:"unknown", rebelChild:false, notes:"", unverified:true },
  ],
  dragons: [
    { id:"s-tairn",  name:"Tairn",  color:"", family:"", sire:"", dam:"", riderId:"s-violet", status:"unknown", notes:"", unverified:true },
    { id:"s-andarna",name:"Andarna",color:"", family:"", sire:"", dam:"", riderId:"s-violet", status:"unknown", notes:"Violet's second bond.", unverified:true },
    { id:"s-sgaeyl", name:"Sgaeyl", color:"", family:"", sire:"", dam:"", riderId:"s-xaden", status:"unknown", notes:"", unverified:true },
    { id:"s-cath",   name:"Cath",   color:"", family:"", sire:"", dam:"", riderId:"s-dain", status:"unknown", notes:"", unverified:true },
    { id:"s-deigh",  name:"Deigh",  color:"", family:"", sire:"", dam:"", riderId:"s-liam", status:"unknown", notes:"", unverified:true },
  ],
  events: [
    { id:"s-ev-threshing", title:"Violet's Threshing", book:"FW", order:10, chapter:"", page:"", edition:"", kind:"event",
      desc:"Violet takes part in Threshing at Basgiath. Add the page, chapter and details from your copy.", chars:["s-violet"], unverified:true },
  ],
  theories: [
    { id:"s-th-example", title:"Example theory — delete me", status:"speculative", confidence:2,
      body:"This is a placeholder showing how a theory works. Pick the timeline events that foreshadow it, then either link the event where it pays off or leave it as 'not yet revealed'. Add evidence with a book, edition and page number, and mark each piece as support or against.",
      foreshadow:["s-ev-threshing"], revealId:"", revealText:"",
      evidence:[{ book:"FW", edition:"Hardcover", page:"123", note:"Example reference — replace with a real one.", stance:"support" }], created:0, updated:0 },
  ],
  // Public notices from the DragonKind library: numbers and transcribers as listed there, summaries paraphrased.
  notices: [
    {
      "id": "s-n-634-23",
      "title": "Public Notice 634.23",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 634",
      "transcriber": "Percival Fitzgibbons",
      "seq": 1,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Conscription rates are doubled in every province until further notice.",
      "cites": []
    },
    {
      "id": "s-n-628-86",
      "title": "Public Notice 628.86",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 628",
      "transcriber": "Cerella Neilwart",
      "seq": 2,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "After the Treaty of Aretia, Tyrrendor's seat in the King's Senarium passes from House Riorson to House Lewellen.",
      "cites": []
    },
    {
      "id": "s-n-628-85",
      "title": "Public Notice 628.85",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 628",
      "transcriber": "Cerella Neilwart",
      "seq": 3,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Records that Aretia was burned by dragons under the treaty that ended the separatist movement. Those who fled survived; the rest remain entombed in the ruins.",
      "cites": []
    },
    {
      "id": "s-n-442-184",
      "title": "Public Notice 442.184",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 442",
      "transcriber": "Corrigan Aligis",
      "seq": 4,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Raiders from the Emerald Sea sacked the Tyrrish village of Kyllendelle. Seaside residents of Tyrrendor and Luceras are asked to stay vigilant and light warning beacons to call the nearest riot.",
      "cites": []
    },
    {
      "id": "s-n-433-231",
      "title": "Public Notice 433.231",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 433",
      "transcriber": "Corrigan Aligis",
      "seq": 5,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Navarrian forces repelled an attempted breach by Poromish troops near the outpost of Athebyne. The attack is called unprovoked, and the commitment to the peace process is restated.",
      "cites": []
    },
    {
      "id": "s-n-210-183",
      "title": "Public Notice 210.183",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 210",
      "transcriber": "Myla Arvinset",
      "seq": 6,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Provincial notices are ended. Regional notices written by local scribes replace them, each needing approval from the Curator of the Scribe Quadrant at Basgiath before posting.",
      "cites": []
    },
    {
      "id": "s-n-209-11",
      "title": "Public Notice 209.11",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 209",
      "transcriber": "Myla Arvinset",
      "seq": 7,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Public notices now override provincial ones, posted for up to sixty days in any village with more than five hundred people.",
      "cites": []
    },
    {
      "id": "s-n-208-271",
      "title": "Public Notice 208.271",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 208",
      "transcriber": "Myla Arvinset",
      "seq": 8,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Queen Alondra splits Tyrrendor into three duchies (Lewellen, Tirvainne and Aretia). The Duchess of Aretia keeps the Tyrrish seat on the Senarium.",
      "cites": []
    },
    {
      "id": "s-n-207-6",
      "title": "Public Notice 207.6",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 207",
      "transcriber": "Myla Arvinset",
      "seq": 9,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Because of increased danger, travel beyond Navarre may only be authorized by the sovereign.",
      "cites": []
    },
    {
      "id": "s-n-207-1",
      "title": "Public Notice 207.1",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 207",
      "transcriber": "Myla Arvinset",
      "seq": 10,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Every duchy signs a Provincial Commitment placing the provincial armies under Queen Alondra's standard against Poromish aggression until the war is declared over.",
      "cites": []
    },
    {
      "id": "s-n-200-417",
      "title": "Public Notice 200.417",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 200",
      "transcriber": "Racel Lightstone",
      "seq": 11,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Guardians may no longer dedicate children to a favored deity. Serving the gods for life must be chosen freely after the age of majority.",
      "cites": []
    },
    {
      "id": "s-n-2-21",
      "title": "Public Notice 2.21",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 2",
      "transcriber": "Byran Firthfelder",
      "seq": 12,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The Migration of the First Year is declared complete. Borders are secured against increasingly militant neighbors, and travel beyond Navarre may be authorized by a duchy's ruling house.",
      "cites": []
    },
    {
      "id": "s-n-1-323",
      "title": "Public Notice 1.323",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 13,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Krovlan forces attacked Elsum, causing four casualties in the mountains near the village of Resson. The area is secured and the attack is called an outlier; the commitment to peace stands.",
      "cites": []
    },
    {
      "id": "s-n-1-249",
      "title": "Public Notice 1.249",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 14,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The Council of Calldyr agrees that Navarre is ruled as a secular kingdom, but its marriage law follows the terms each god sets in their temples.",
      "cites": []
    },
    {
      "id": "s-n-1-3",
      "title": "Public Notice 1.3",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 15,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "As promised in the Unification Scrolls, the borders stay open for twelve months to anyone who wants to live under Navarre's wards and laws.",
      "cites": []
    },
    {
      "id": "s-n-1-2",
      "title": "Public Notice 1.2",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 16,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "The scribes of Basgiath War College take over announcing and recording public notices, posted beside provincial ones for at least thirty days in villages with more than fifty people.",
      "cites": []
    },
    {
      "id": "s-n-1-1",
      "title": "Public Notice 1.1",
      "source": "dragonkind",
      "url": "https://dragonkind.com/library",
      "inWorld": "Year 1",
      "transcriber": "Tobias Malthus",
      "seq": 17,
      "book": "OT",
      "read": false,
      "theoryIds": [],
      "summary": "Calldyr, Elsum, Luceras, Morainne and Tyrrendor accept the Unification Scrolls and swear fealty to King Reginald Navarrius. The kingdom is named Navarre and the calendar restarts at year 1.",
      "cites": []
    }
  ],
};
